#!/usr/bin/env python

import sys
import fileinput
import collections


def main():
    if len(sys.argv) == 1:
        all_vocab = True
    else:
        all_vocab = False
        top_n = int(sys.argv[1])

    word_counter = collections.Counter()

    for line in fileinput.input(files="-"):
        words = line.strip().split()
        word_counter.update(words)

    if all_vocab:
        vocab = [word for (word, _) in word_counter.most_common()]
    else:
        vocab = [word for (word, _) in word_counter.most_common(top_n)]
    print(*vocab, sep="\n")


if __name__ == "__main__":
    main()
