#!/usr/bin/env python

import fileinput
import nltk


def main():
    for line in fileinput.input():
        words = nltk.word_tokenize(line)
        print(*words)


if __name__ == "__main__":
    main()
